version: "3.9"

services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - URL=daxis.io
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - STAGING=true
    volumes:
      - ./data/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
