version: "3.9"

services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:7-alpine
    restart: always
    networks:
      - wordpress

  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: mariadb:11-jammy
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - wordpress

  wordpress:
    container_name: wordpress
    hostname: wordpress
    build:
      context: ./docker/wordpress
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mariadb
      - redis
    volumes:
      - ./data/html:/var/www/html
      - ./data/swag/php.ini:/usr/local/etc/php/conf.d/php_optional.ini
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_REDIS_HOST', 'redis');
        define('WP_REDIS_PORT', '6379');
        define('WP_MEMORY_LIMIT', '768M');
        define('WP_MAX_MEMORY_LIMIT', '1024M');
        define('WP_DEBUG', false);
        define('WP_DEBUG_LOG', false);
        define('WP_DEBUG_DISPLAY', false);
        define('WP_CACHE', true);
    networks:
      - wordpress

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    hostname: swag
    cap_add:
      - NET_ADMIN
    environment:
      - URL=${SITE_DOMAIN}
      - TZ=${TIMEZONE}
      - PUID=1000
      - PGID=1000
      - VALIDATION=${VALIDATION_TYPE}
      - DNSPLUGIN=${DNS_PLUGIN}
      - STAGING=${STAGING}
      - EMAIL=${EMAIL}
      - CERTPROVIDER=${CERT_PROVIDER}
    volumes:
      - ./data/swag:/config
      - ./data/html:/var/www/html
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    networks:
      - wordpress

networks:
  wordpress:
    driver: bridge
    name: wordpress
